---

- hosts: "{{host}}"
  vars:
    - virtenv_path: "{{zstack_root}}/virtualenv/sftpbackupstorage/"
    - sftp_root: "{{zstack_root}}/sftpbackupstorage"
    - file_root: "files/sftpbackupstorage"
    - pip_url: "{{pypi_url|default('https://pypi.python.org/simple/')}}"
    - proxy: "{{http_proxy|default('')}}"
    - sproxy: "{{https_proxy|default('')}}"
    - chroot_env: "{{chroot|default('false')}}"
    - yum_repos: "{{yum_repo|default('false')}}"

  tasks:
    - include: zstacklib.yaml

    - name: create root directories
      shell: "mkdir -p {{item}}"
      with_items:
        - "{{sftp_root}}"
        - "{{virtenv_path}}"

    - name: install sftp backup storage related packages on RedHat based OS from local
      when: ansible_os_family == 'RedHat' and yum_repos != 'false'
      shell: "yum --disablerepo=* --enablerepo={{yum_repos}} --nogpgcheck install -y openssh-clients"

    - name: install sftp backup storage related packages on RedHat based OS from online
      when: ansible_os_family == 'RedHat' and yum_repos == 'false'
      shell: "yum --nogpgcheck install -y openssh-clients "

    - name: install sftp backup storage related packages on Debian based OS
      when: ansible_os_family == 'Debian'
      apt: pkg="{{item}}"
      with_items:
        - openssh-client

    - shell: virtualenv --version | grep "12.1.1"
      register: virtualenv_ret
      ignore_errors: True

    - name: install virtualenv
      pip: name=virtualenv version=12.1.1 extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}"
      when: virtualenv_ret.rc != 0

    - name: create virtualenv
      shell: "rm -rf {{virtenv_path}} && rm -f {{sftp_root}}/{{pkg_sftpbackupstorage}} && rm -f {{sftp_root}}/{{pkg_zstacklib}} && virtualenv {{virtenv_path}}"

    - name: add public key
      authorized_key: user=root key="{{ lookup('file', 'files/sftpbackupstorage/id_rsa.sftp.pub') }}"

    - name: copy zstacklib
      copy: src="files/zstacklib/{{pkg_zstacklib}}" dest="{{sftp_root}}/{{pkg_zstacklib}}"
      notify:
        - install zstacklib

    - name: copy sftp
      copy: src="{{file_root}}/{{pkg_sftpbackupstorage}}" dest="{{sftp_root}}/{{pkg_sftpbackupstorage}}"
      notify:
        - install sftp

    # only for os using init.d not systemd
    - name: copy sftp backup storage service file
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
      copy: src="{{file_root}}/zstack-sftpbackupstorage" dest=/etc/init.d/ mode=755

    - meta: flush_handlers

    - name: restart sftp
      service: name=zstack-sftpbackupstorage state=restarted enabled=yes
      when: chroot_env == 'false'

  handlers:
    - name: install zstacklib
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{sftp_root}}/{{pkg_zstacklib}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}"

    - name: install sftp
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{sftp_root}}/{{pkg_sftpbackupstorage}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}"

