#!/bin/sh

# the following is chkconfig init header
#
# zstack-aliyunagent:   zstack aliyun agent daemon
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by zstack management server \
#               to perform aliyun related operations\
#               See http://zstack.org
#
# processname: aliyunagent
# pidfile: /var/run/zstack/aliyunagent.pid
#

check_status() {
	pidfile='/var/run/zstack/aliyunagent.pid'
	if [ ! -f $pidfile ]; then
		echo "zstack aliyun agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "zstack aliyun agent is running, pid is $pid"
			exit 0
		else
			echo "zstack aliyun agent is stopped, but pidfile at $pidfile is not cleaned. It may be caused by aliyun agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/zstack/virtualenv/aliyun/bin/activate && python -c "from aliyunagent import kdaemon; kdaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ zstack aliyun agent .... SUCCESS"
    exit 0
else
    echo "$@ zstack aliyun agent .... FAILED"
    exit 1
fi
