#!/bin/sh

# the following is chkconfig init header
#
# zstack-kvmagent:   zstack kvm agent daemon
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by zstack management server \
#               to perform kvm related operations\
#               See http://zstack.org
#
# processname: kvmagent
# pidfile: /var/run/zstack/kvmagent.pid
#

check_status() {
	pidfile='/var/run/zstack/xenagent.pid'
	if [ ! -f $pidfile ]; then
		echo "zstack xen agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "zstack kvm agent is running, pid is $pid"
			exit 0
		else
			echo "zstack kvm agent is stopped, but pidfile at $pidfile is not cleaned. It may be caused by kvm agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/zstack/virtualenv/xen/bin/activate && python -c "from kvmagent import kdaemon; kdaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ zstack xen agent .... SUCCESS"
    exit 0
else
    echo "$@ zstack xen agent .... FAILED"
    exit 1
fi
